version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: myappuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: myappdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  db_data:
